### ISSUE TITLE
Take ownership request

### ISSUE THREAD

**Issue by tom-englert** [tom-englert/JetBrainsAnnotations#6]

**Comment by tom-englert** [comment]
@SimonCropp my nuget account name is also "tom-englert"

**Comment by tom-englert** [comment]
@SimonCropp will you give me write access to this repository, or should I forward to my fork in the readme.md?

**Comment by SimonCropp** [comment]
I did a github transfer of the repo. If u accept that gh should handle redirects. Did u not get the email?

**Comment by tom-englert** [comment]
Nope, only the one from nuget

**Comment by SimonCropp** [comment]
i cant do it while u have a fork
![image](https://user-images.githubusercontent.com/122666/29002565-8a471dba-7ae8-11e7-8402-af46f3e08ffa.png)

**Comment by tom-englert** [comment]
Ok, removed that
